import type { Metadata } from 'next'
import {
    Geist,
    Geist_Mono,
    Playfair_Display,
    Chivo,
    Chivo_Mono,
} from 'next/font/google'
import './globals.css'
import TanstackQueryProvider from '@/providers/tanstack-query-provider'
import { ThemeProvider } from '@/providers/theme-provider'
import { ToasterWithTheme } from '@/components/ToasterWithTheme'

const playfairDisplay = Playfair_Display({
    variable: '--font-playfair-display-serif',
    subsets: ['latin'],
})
const chivoSans = Chivo({
    variable: '--font-chivo-sans',
    subsets: ['latin'],
})

const chivoMono = Chivo_Mono({
    variable: '--font-chivo-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${playfairDisplay.variable} ${chivoMono.variable} ${chivoSans.variable} antialiased`}
                suppressHydrationWarning
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <TanstackQueryProvider>{children}</TanstackQueryProvider>
                    <ToasterWithTheme />
                </ThemeProvider>
            </body>
        </html>
    )
}
